name: 每週資安新聞周報

on:
  schedule:
    - cron: '0 0 * * 1'  # 每週一 00:00 UTC（台灣時間 08:00）
  workflow_dispatch:  # 允許手動觸發

permissions:
  contents: write #允許Actions推送內容到倉庫

jobs:
  fetch-and-summarize-news:
    runs-on: ubuntu-latest

    steps:
      - name: 取得 Repository
        uses: actions/checkout@v4

      - name: 設置 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝 Python 依賴套件
        run: pip install -r requirements.txt

      - name: 抓取資安新聞連結
        run: python scripts/fetch_news_link.py

      - name: 抓取資安新聞(markdown格式)
        run: python scripts/download_articles_markdown.py  

      - name: AI Agent產生新聞摘要（Groq API）
        run: python scripts/summarize_news_groq.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: 整理新聞摘要
        run: python scripts/merge_summary_by_section.py

      - name: 產出資安週報（Groq API）
        run: python scripts/generate_weekly_report_groq.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}  

      - name: 發送 LINE 通知
        run: python scripts/send_notification_line.py
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}

      - name: 發送 Discord 通知
        run: python scripts/send_notification_discord.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}    
