name: 每週資安新聞周報

on:
  schedule:
    - cron: '0 0 * * 1'  # 每週一 00:00 UTC（台灣時間 08:00）
  workflow_dispatch:  # 允許手動觸發

permissions:
  contents: write #允許Actions推送內容到倉庫

jobs:
  fetch-and-summarize-news:
    runs-on: ubuntu-latest

    steps:
      - name: 取得 Repository
        uses: actions/checkout@v4

      - name: 設置 Python 環境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 安裝 Python 依賴套件
        run: pip install -r requirements.txt

      - name: 抓取資安新聞連結
        run: python scripts/fetch_news_link.py

      - name: 抓取資安新聞(markdown格式)
        run: python scripts/download_articles_markdown.py  

      - name: AI Agent產生新聞摘要1（Groq API）
        run: python scripts/summarize_news_groq.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: 抓取NICS(json格式)
        run: python scripts/fetch_nics.py

      - name: 抓取TheHackersNews(json格式)
        run: python scripts/fetch_thehackersnews.py

      - name: 抓取TWCERT(json格式)
        run: python scripts/fetch_twcert.py

      - name: AI Agent產生新聞摘要2（Groq API）
        run: python scripts/groq_summarize_json.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}  

      - name: 整理新聞摘要
        run: python scripts/merge_summary_by_section.py

      - name: 分離新聞摘要
        run: python scripts/separation.py 

      - name: AI Agent產生security摘要（Groq API）
        run: python scripts/generate_report_groq_security.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}    

      - name: AI Agent產生threat摘要（Groq API）
        run: python scripts/generate_report_groq_threat.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

      - name: 發送 Discord 通知 1
        run: python scripts/send_notification_discord_security.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}     

      - name: 發送 Discord 通知 2
        run: python scripts/send_notification_discord_threat.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}     

      - name: AI Agent產生incident摘要（Groq API）
        run: python scripts/generate_report_groq_incident.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}     

      - name: AI Agent產生future摘要（Groq API）
        run: python scripts/generate_report_groq_future.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }} 

      - name: 發送 Discord 通知 3
        run: python scripts/send_notification_discord_incident.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}      

      - name: 發送 Discord 通知 4
        run: python scripts/send_notification_discord_future.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}      

      - name: 發送 LINE 通知
        run: python scripts/send_notification_line.py
        env:
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }} 
